// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./functions/context.ts";
import * as $$$0 from "./loaders/fresh.gen.ts";
import * as $$$1 from "./loaders/main.ts";
import * as $$$2 from "./loaders/commons.tsx";
import * as $$$3 from "./loaders/manifest.gen.ts";
import * as $$$4 from "./loaders/import_map.ts";
import * as $$$5 from "./loaders/files/serve.tsx";
import * as $$$6 from "./loaders/fs/kvfs.ts";
import * as $$$$0 from "./handlers/newPlayground.ts";
import * as $$$$$$0 from "./sections/Topbar.tsx";
import * as $$$$$$1 from "./sections/FileTree.tsx";
import * as $$$$$$2 from "./sections/Links.tsx";
import * as $$$$$$$$$0 from "./actions/new.ts";
import * as $$$$$$$$$1 from "./actions/files/remove.ts";
import * as $$$$$$$$$2 from "./actions/files/createOrEdit.ts";
import * as $$$$$$$$$3 from "./actions/deploy.ts";
import * as $$$$$$$$$4 from "./actions/useTemplate.ts";
import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "functions": {
    "play/functions/context.ts": $0,
  },
  "loaders": {
    "play/loaders/commons.tsx": $$$2,
    "play/loaders/files/serve.tsx": $$$5,
    "play/loaders/fresh.gen.ts": $$$0,
    "play/loaders/fs/kvfs.ts": $$$6,
    "play/loaders/import_map.ts": $$$4,
    "play/loaders/main.ts": $$$1,
    "play/loaders/manifest.gen.ts": $$$3,
  },
  "handlers": {
    "play/handlers/newPlayground.ts": $$$$0,
  },
  "sections": {
    "play/sections/FileTree.tsx": $$$$$$1,
    "play/sections/Links.tsx": $$$$$$2,
    "play/sections/Topbar.tsx": $$$$$$0,
  },
  "actions": {
    "play/actions/deploy.ts": $$$$$$$$$3,
    "play/actions/files/createOrEdit.ts": $$$$$$$$$2,
    "play/actions/files/remove.ts": $$$$$$$$$1,
    "play/actions/new.ts": $$$$$$$$$0,
    "play/actions/useTemplate.ts": $$$$$$$$$4,
  },
  "apps": {
    "play/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "play",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
