// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Topbar.tsx";
import * as $$$$$$1 from "./sections/Links.tsx";
import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/play/sections/Links.tsx": $$$$$$1,
    "deco-sites/play/sections/Topbar.tsx": $$$$$$0,
  },
  "apps": {
    "deco-sites/play/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/play",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
